[connections.postgresql]
host = "ep-misty-dawn-a2l7mwke-pooler.eu-central-1.aws.neon.tech"
database = "scraped_nickel_reviews" # Votre nom de base de données
user = "neondb_owner"
password = "npg_nMbf3cliNj0y"
sslmode = "require"
